<a href="https://colab.research.google.com/github/LucasEdPS/Estudo/blob/main/aula1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print(1.7e308)

1.7e+308


In [2]:
print(1.82e308)

inf


In [3]:
print(1.83e309 – 1.82e308)

SyntaxError: invalid character '–' (U+2013) (<ipython-input-3-82e4c1c1f8bd>, line 1)

In [5]:
import sys
menor_incremento = sys.float_info.epsilon
print("Menor incremento entre números de ponto flutuante:", menor_incremento)

Menor incremento entre números de ponto flutuante: 2.220446049250313e-16


In [18]:
x=1.0; y=1.0*10**15;z=1.0*10**16

In [19]:
print(y-y+x,y+(-y+x),z-z+x,z+(-z+x))

1.0 1.0 1.0 0.0


In [22]:
vetor_inteiro = [1, 2, 3, 4, 5]
print(vetor_inteiro)

[1, 2, 3, 4, 5]


In [23]:
import numpy as np
vetor_numpy = np.array([1, 2, 3, 4, 5])
print(vetor_numpy)

[1 2 3 4 5]


In [24]:
from array import array
# Criando um vetor usando o módulo array
vetor_array = array('i', [1, 2, 3, 4, 5])
print(vetor_array)

array('i', [1, 2, 3, 4, 5])


In [25]:
import math
# Definindo um vetor como uma lista
vetor = [3, 4]
# Calculando a norma (norma L2 ou euclidiana) manualmente
norma = math.sqrt(sum(x**2 for x in vetor))
print("Norma do vetor:", norma)

Norma do vetor: 5.0


In [26]:
# Definindo um vetor usando NumPy
vetor_numpy = np.array([3, 4])
# Calculando a norma usando NumPy
norma_numpy = np.linalg.norm(vetor_numpy)
print("Norma do vetor (NumPy):", norma_numpy)

Norma do vetor (NumPy): 5.0


In [27]:
import numpy as np
vetor_numpy = np.array([3, 4])
# Calculando a norma L1 usando NumPy
norma_L1 = np.linalg.norm(vetor_numpy, ord=1)
print("Norma L1 do vetor:", norma_L1)

Norma L1 do vetor: 7.0


In [28]:
matriz = [
[1, 2, 3], # Primeira linha
[4, 5, 6], # Segunda linha
[7, 8, 9] # Terceira linha
]
print(matriz)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [30]:
# Criando uma matriz usando NumPy
matriz_numpy = np.array([
[1, 2, 3], # Primeira linha
[4, 5, 6], # Segunda linha
[7, 8, 9] # Terceira linha
])
print(matriz_numpy)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [31]:
# Gerando uma matriz 3x3 de valores aleatórios entre 0 e 1
matriz_aleatoria_uniforme = np.random.rand(3, 3)
print("Matriz aleatória (distribuição uniforme):\n", matriz_aleatoria_uniforme)

Matriz aleatória (distribuição uniforme):
 [[0.02004286 0.59837058 0.98358207]
 [0.93983573 0.72517669 0.4412994 ]
 [0.74841643 0.66476245 0.79493677]]


In [32]:
# Gerando uma matriz 3x3 de valores aleatórios com distribuição normal
matriz_aleatoria_normal = np.random.randn(3, 3)
print("Matriz aleatória (distribuição normal):\n", matriz_aleatoria_normal)

Matriz aleatória (distribuição normal):
 [[ 0.28873711  0.47874922 -1.25897984]
 [-1.10244048  0.96381607  0.14075481]
 [-3.26628258 -0.28168361  0.66584507]]


In [36]:
# Criando uma matriz usando NumPy
matriz = np.array([
[1, 2],
[3, 4]
])
print(matriz)
# Calculando a norma de matriz usando NumPy
norma_matriz = np.linalg.norm(matriz)
print("Norma da matriz:", norma_matriz)

[[1 2]
 [3 4]]
Norma da matriz: 5.477225575051661


In [38]:
# Criando uma matriz
matriz =[
[1, 2],
[3, 4]
]
print(matriz)
# Calculando a norma de matriz usando NumPy
norma_matriz = np.linalg.norm(matriz)
print("Norma da matriz:", norma_matriz)

[[1, 2], [3, 4]]
Norma da matriz: 5.477225575051661


In [39]:
# Criando uma matriz
matriz =[
[1, 2],
[3, 4]
]
# Criando uma matriz Numpy a partir da matriz
matriz = np.array(matriz)
print(matriz)
# Calculando a norma de matriz usando NumPy
norma_matriz = np.linalg.norm(matriz)
print("Norma da matriz:", norma_matriz)

[[1 2]
 [3 4]]
Norma da matriz: 5.477225575051661
