<a href="https://colab.research.google.com/github/LucasEdPS/Estudo/blob/main/Test_carteira.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [441]:
import yfinance as yf
import numpy as np

In [442]:
#dados = formular_dados.acoes_ibov
dados = ['ABEV3.SA', 'EGIE3.SA', 'RECV3.SA', 'TUPY3.SA', 'VALE3.SA', 'BCFF11.SA', 'HGLG11.SA', 'TAEE4.SA', 'VIVT3.SA', 'WEGE3.SA', 'RADL3.SA']
acoes = sorted(dados)
display(acoes)

['ABEV3.SA',
 'BCFF11.SA',
 'EGIE3.SA',
 'HGLG11.SA',
 'RADL3.SA',
 'RECV3.SA',
 'TAEE4.SA',
 'TUPY3.SA',
 'VALE3.SA',
 'VIVT3.SA',
 'WEGE3.SA']

In [443]:
# Obtendo os dados das ações
dados_acoes = yf.download(acoes, period = 'max', interval = '1mo')['Adj Close']
display(dados_acoes)

[*********************100%%**********************]  11 of 11 completed


Ticker       ABEV3.SA  BCFF11.SA   EGIE3.SA   HGLG11.SA   RADL3.SA   RECV3.SA  \
Date                                                                            
2000-02-01   0.260933        NaN        NaN         NaN   0.005444        NaN   
2000-03-01   0.338124        NaN        NaN         NaN   0.005444        NaN   
2000-04-01   0.349149        NaN        NaN         NaN   0.005444        NaN   
2000-05-01   0.338124        NaN        NaN         NaN   0.005444        NaN   
2000-06-01   0.422646        NaN        NaN         NaN   0.028791        NaN   
...               ...        ...        ...         ...        ...        ...   
2023-11-01  13.009971   8.285843  43.326672  156.034409  27.982853  19.277008   
2023-12-01  13.047983   9.157112  45.149380  157.702759  29.298286  21.146294   
2024-01-01  13.080000   8.972036  40.580002  161.990189  25.299999  23.049999   
2024-02-01  12.580000   8.921073  42.020000  167.765839  26.639999  23.000000   
2024-03-01  12.680000   9.080000  40.549999  169.050003  26.670000  21.799999   

Ticker       TAEE4.SA     TUPY3.SA   VALE3.SA   VIVT3.SA   WEGE3.SA  
Date                                                                 
2000-02-01        NaN  1440.704102   1.554754  10.475186   0.106008  
2000-03-01        NaN  1440.704102   1.524269   9.150742   0.106008  
2000-04-01        NaN  1440.704102   1.524269   8.130314   0.106008  
2000-05-01        NaN  1440.704102   1.593623   8.277808   0.100708  
2000-06-01        NaN  1440.704102   1.714420   6.047315   0.100708  
...               ...          ...        ...        ...        ...  
2023-11-01  11.814231    25.448103  73.124039  52.256062  33.839176  
2023-12-01  12.609901    28.794971  77.199997  52.929569  36.531265  
2024-01-01  12.157793    26.220455  67.760002  51.360001  32.072197  
2024-02-01  11.860000    25.600000  66.989998  54.480000  36.386177  
2024-03-01  11.730000    26.650000  66.809998  52.150002  37.240002  

[290 rows x 11 columns]

In [444]:
# Calculando os retornos
dados_retornos = dados_acoes.pct_change()
display(dados_retornos)

Ticker      ABEV3.SA  BCFF11.SA  EGIE3.SA  HGLG11.SA  RADL3.SA  RECV3.SA  \
Date                                                                       
2000-02-01       NaN        NaN       NaN        NaN       NaN       NaN   
2000-03-01  0.295826        NaN       NaN        NaN  0.000000       NaN   
2000-04-01  0.032606        NaN       NaN        NaN  0.000000       NaN   
2000-05-01 -0.031576        NaN       NaN        NaN  0.000000       NaN   
2000-06-01  0.249973        NaN       NaN        NaN  4.288929       NaN   
...              ...        ...       ...        ...       ...       ...   
2023-11-01  0.064541   0.120344  0.106870   0.028525  0.090464 -0.045323   
2023-12-01  0.002922   0.105152  0.042069   0.010692  0.047009  0.096970   
2024-01-01  0.002454  -0.020211 -0.101206   0.027187 -0.136468  0.090025   
2024-02-01 -0.038226  -0.005680  0.035485   0.035654  0.052964 -0.002169   
2024-03-01  0.007949   0.017815 -0.034983   0.007655  0.001126 -0.052174   

Ticker      TAEE4.SA  TUPY3.SA  VALE3.SA  VIVT3.SA  WEGE3.SA  
Date                                                          
2000-02-01       NaN       NaN       NaN       NaN       NaN  
2000-03-01       NaN  0.000000 -0.019608 -0.126436  0.000000  
2000-04-01       NaN  0.000000  0.000000 -0.111513  0.000000  
2000-05-01       NaN  0.000000  0.045500  0.018141 -0.049997  
2000-06-01       NaN  0.000000  0.075801 -0.269455  0.000000  
...              ...       ...       ...       ...       ...  
2023-11-01  0.076652  0.064720  0.070290  0.168572  0.035747  
2023-12-01  0.067348  0.131517  0.055740  0.012889  0.079555  
2024-01-01 -0.035853 -0.089409 -0.122280 -0.029654 -0.122062  
2024-02-01 -0.024494 -0.023663 -0.011364  0.060748  0.134508  
2024-03-01 -0.010961  0.041016 -0.002687 -0.042768  0.023466  

[290 rows x 11 columns]

In [445]:
# Calculando a matriz de covariância
covariance_matrix = dados_retornos.cov()
display(covariance_matrix)

Ticker     ABEV3.SA  BCFF11.SA  EGIE3.SA  HGLG11.SA  RADL3.SA  RECV3.SA  \
Ticker                                                                    
ABEV3.SA   0.006420   0.000791  0.001207   0.000666  0.005574 -0.002463   
BCFF11.SA  0.000791   0.004303  0.000768   0.001203  0.001527  0.002362   
EGIE3.SA   0.001207   0.000768  0.007696   0.000924  0.000514  0.000359   
HGLG11.SA  0.000666   0.001203  0.000924   0.002514  0.000570  0.000511   
RADL3.SA   0.005574   0.001527  0.000514   0.000570  0.110734  0.000447   
RECV3.SA  -0.002463   0.002362  0.000359   0.000511  0.000447  0.018766   
TAEE4.SA   0.001562   0.000682  0.001622   0.000373  0.001541  0.000338   
TUPY3.SA   0.000477   0.001268  0.001205   0.000718 -0.001215  0.003733   
VALE3.SA   0.001139   0.001036  0.000022   0.000884  0.002792  0.000853   
VIVT3.SA   0.001283   0.000195  0.001013   0.000546 -0.003586 -0.000620   
WEGE3.SA   0.001172   0.000895  0.001154   0.000479  0.001685  0.002590   

Ticker     TAEE4.SA  TUPY3.SA  VALE3.SA  VIVT3.SA  WEGE3.SA  
Ticker                                                       
ABEV3.SA   0.001562  0.000477  0.001139  0.001283  0.001172  
BCFF11.SA  0.000682  0.001268  0.001036  0.000195  0.000895  
EGIE3.SA   0.001622  0.001205  0.000022  0.001013  0.001154  
HGLG11.SA  0.000373  0.000718  0.000884  0.000546  0.000479  
RADL3.SA   0.001541 -0.001215  0.002792 -0.003586  0.001685  
RECV3.SA   0.000338  0.003733  0.000853 -0.000620  0.002590  
TAEE4.SA   0.004070  0.001861  0.000667  0.000507  0.001163  
TUPY3.SA   0.001861  0.019932  0.000614  0.000512  0.000936  
VALE3.SA   0.000667  0.000614  0.010348  0.001243  0.001228  
VIVT3.SA   0.000507  0.000512  0.001243  0.005059  0.000840  
WEGE3.SA   0.001163  0.000936  0.001228  0.000840  0.007491

In [446]:
# Calculando a media dos retornos
media_retornos = dados_retornos.mean()
display(media_retornos)

Ticker
ABEV3.SA     0.016842
BCFF11.SA    0.032452
EGIE3.SA     0.016221
HGLG11.SA    0.005767
RADL3.SA     0.049443
RECV3.SA     0.015289
TAEE4.SA     0.015728
TUPY3.SA     0.012266
VALE3.SA     0.018125
VIVT3.SA     0.008085
WEGE3.SA     0.024016
dtype: float64

In [447]:
# tornando as matrizes em array
matriz_cov = np.array(covariance_matrix)
retornos = np.array(media_retornos)
display(matriz_cov,retornos)

array([[ 6.42038664e-03,  7.90707394e-04,  1.20692794e-03,
         6.65904661e-04,  5.57374225e-03, -2.46290598e-03,
         1.56222150e-03,  4.76948054e-04,  1.13883036e-03,
         1.28340398e-03,  1.17202518e-03],
       [ 7.90707394e-04,  4.30300819e-03,  7.68436573e-04,
         1.20288271e-03,  1.52703241e-03,  2.36194867e-03,
         6.82476616e-04,  1.26839474e-03,  1.03582606e-03,
         1.94906410e-04,  8.95203823e-04],
       [ 1.20692794e-03,  7.68436573e-04,  7.69590163e-03,
         9.23579122e-04,  5.14383075e-04,  3.59024592e-04,
         1.62172728e-03,  1.20463631e-03,  2.21944690e-05,
         1.01335011e-03,  1.15370828e-03],
       [ 6.65904661e-04,  1.20288271e-03,  9.23579122e-04,
         2.51392005e-03,  5.69966391e-04,  5.11083185e-04,
         3.73022092e-04,  7.17593554e-04,  8.84332331e-04,
         5.46277512e-04,  4.78872134e-04],
       [ 5.57374225e-03,  1.52703241e-03,  5.14383075e-04,
         5.69966391e-04,  1.10733715e-01,  4.46657616e-04,
  

array([0.01684223, 0.0324523 , 0.01622065, 0.00576685, 0.04944265,
       0.01528906, 0.01572792, 0.01226571, 0.0181254 , 0.00808538,
       0.02401627])

In [448]:
# transformando a matriz covariancia na matra A da Função para o metodo de newton
matriz = np.empty([len(acoes),len(acoes)])

for i in range(len(acoes)):
    matriz[i] = (matriz_cov[i]*2)

# Adicionando uma coluna de uns à direita da matriz para se tornar A
nova_coluna = np.ones((matriz.shape[0], 1))
matriz_a = np.hstack((matriz, nova_coluna))

# Adicionando uma linha de uns e uma linha de zeros na parte inferior da matriz expandida para se tornar A
nova_linha_1 = np.ones((1, matriz_a.shape[1]))
matriz_a = np.vstack((matriz_a, nova_linha_1))

# Matriz A finalizada
matriz_a[len(acoes),len(acoes)] = 0
display(matriz_a)

array([[ 1.28407733e-02,  1.58141479e-03,  2.41385588e-03,
         1.33180932e-03,  1.11474845e-02, -4.92581195e-03,
         3.12444300e-03,  9.53896109e-04,  2.27766071e-03,
         2.56680797e-03,  2.34405035e-03,  1.00000000e+00],
       [ 1.58141479e-03,  8.60601637e-03,  1.53687315e-03,
         2.40576542e-03,  3.05406482e-03,  4.72389734e-03,
         1.36495323e-03,  2.53678948e-03,  2.07165212e-03,
         3.89812819e-04,  1.79040765e-03,  1.00000000e+00],
       [ 2.41385588e-03,  1.53687315e-03,  1.53918033e-02,
         1.84715824e-03,  1.02876615e-03,  7.18049184e-04,
         3.24345456e-03,  2.40927261e-03,  4.43889380e-05,
         2.02670022e-03,  2.30741657e-03,  1.00000000e+00],
       [ 1.33180932e-03,  2.40576542e-03,  1.84715824e-03,
         5.02784010e-03,  1.13993278e-03,  1.02216637e-03,
         7.46044184e-04,  1.43518711e-03,  1.76866466e-03,
         1.09255502e-03,  9.57744268e-04,  1.00000000e+00],
       [ 1.11474845e-02,  3.05406482e-03,  1.0287661

In [449]:

# Frunçõ que calcula o gradiente da função de otimização
def gradiente(p, matriz):
    grad = np.dot(p, matriz)
    grad[len(acoes)] = grad[len(acoes)]-1
    return grad

In [450]:
# Definindo a função do gradiente que irá otimizar a carteira
def newton_raphson(p, q):
    d = gradiente(p,q)
    d = np.array(d)
    d = d*-1
    k = 0
    pant = d.copy()
    p = p + np.linalg.solve(q, d)
    while np.linalg.norm(p - pant) / np.linalg.norm(p) > 1e-10:
        pant = np.array(p)
        k += 1
        p = p + np.linalg.solve(q, d)
        d = gradiente(p,q)
        d = np.array(d)
        d = d*-1
        if k == 1000:
            break
    print(f'Executado {k} vezes')
    return p

In [451]:
# Definindo a função do gradiente que irá otimizar a carteira
def newton_raphson_test(p, q):
    d = gradiente(p,q)
    d = np.array(d)
    d = d*-1
    k = 0
    pant = d.copy()
    inv = np.linalg.inv(q)
    p = p + np.dot(d,inv)
    while np.linalg.norm(p - pant) / np.linalg.norm(p) > 1e-10:
        pant = np.array(p)
        k += 1
        p = p + np.dot(d,inv)
        d = gradiente(p,q)
        d = np.array(d)
        d = d*-1
        if k == 1000:
            break
    print(f'Executado {k} vezes')
    return p

In [452]:
# Definindo o ponto inicial para o gradiente
ponto = np.zeros(len(acoes))
ponto_zero = np.append(ponto, 1)
display(ponto_zero)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.])

In [453]:
# Minimizando a carteira
carteira_otimizada = newton_raphson(ponto_zero,matriz_a)
display(carteira_otimizada)

Executado 3 vezes


array([ 0.06464322,  0.0989608 ,  0.03447189,  0.32540462,  0.00591573,
        0.04474972,  0.17208818,  0.00949397,  0.03381413,  0.15970496,
        0.05075277, -0.00250132])

In [454]:
# Função que calcula o risco a qual foi minimizada
def funcao_f(p):
    return (np.dot(np.dot(p, matriz_cov), p))

In [457]:
carteira_minimizada = np.zeros(len(acoes))

for i in range(len(acoes)):
    carteira_minimizada[i] = carteira_otimizada[i]

i=0
for acao in acoes:
    print(f'{acao}:', f'Alocar {carteira_minimizada[i]*100:,.0f}% do seu capital')
    i += 1


ABEV3.SA: Alocar 6% do seu capital
BCFF11.SA: Alocar 10% do seu capital
EGIE3.SA: Alocar 3% do seu capital
HGLG11.SA: Alocar 33% do seu capital
RADL3.SA: Alocar 1% do seu capital
RECV3.SA: Alocar 4% do seu capital
TAEE4.SA: Alocar 17% do seu capital
TUPY3.SA: Alocar 1% do seu capital
VALE3.SA: Alocar 3% do seu capital
VIVT3.SA: Alocar 16% do seu capital
WEGE3.SA: Alocar 5% do seu capital


In [456]:
retorno_esperado = np.dot(carteira_minimizada, retornos)
risco_carteira = funcao_f(carteira_minimizada)

print(f'Esse é o retorno esperado para sua carteira: {retorno_esperado*100}%')
print(f'O risco mais baixo encontrado para sua carteira é: {risco_carteira*100}%')

Esse é o retorno esperado para sua carteira: 1.3658728988908555%
O risco mais baixo encontrado para sua carteira é: 0.12506615234301757%
